spring:
  application:
    name: credit-service
  datasource:
    url: jdbc:mysql://localhost:3306/mojabaza
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
