spring:
  application:
    name: gateway-service
server:
  port: 4200
zuul:
  prefix: /api
  routes:
    credit-service:
      path: /credit/**
      serviceId: credit-service
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000