spring:
  application:
    name: gateway-service
server:
  port: 4200
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  prefix: /api
  routes:
    credit-service:
      path: /credit/**
      serviceId: credit-service
